#!/usr/bin/env zsh

# Install Homebrew
if ! command -v brew &> /dev/null; then
    echo "Homebrew not found. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew is already installed. Updating..."
    brew update
fi

# Add Homebrew to PATH if not already added
if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
    export PATH="/usr/local/bin:$PATH"
    echo "Homebrew added to PATH. Please restart your shell or run 'source ~/.zshrc' to apply changes."
fi

# List of Homebrew packages
packages=("stow" "neovim" "ripgrep" "node")

# List of Homebrew casks
casks=("iterm2" "font-meslo-lg-nerd-font")

# Function to check and install Homebrew packages
check_and_install_packages() {
    for package in "${packages[@]}"; do
        if brew list "$package" &>/dev/null; then
            echo "$package is already installed."
        else
            echo "Installing $package..."
            brew install "$package"
        fi
    done
}

# Function to check and install Homebrew casks
check_and_install_casks() {
    for cask in "${casks[@]}"; do
        if brew list --cask "$cask" &>/dev/null; then
            echo "$cask is already installed."
        else
            echo "Installing $cask..."
            brew install --cask "$cask"
        fi
    done
}

# Run the functions to check and install packages and casks
check_and_install_packages
check_and_install_casks

# Check if NVM is installed
if [ -f "$HOME/.nvm/nvm.sh" ]; then
    echo "NVM is installed."
else
    echo "NVM is not installed."
    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
fi